### ISSUE TITLE
[Feature Request] Missing Exit Room Button

### ISSUE THREAD

**Issue by mohan-bee** [mohan-bee/DummyChat-React#1]
After Successful SignIn And After Entering the Room , The User Was not able to exit the room.

So We need a Exit Button and bring the page back to the "Enter Your room page"

**Comment by SahitSunny** [comment]
can i take this task?

**Comment by SahitSunny** [comment]
i had added this feature, does it looks fine?
![Screenshot 2024-11-25 010402](https://github.com/user-attachments/assets/927c995d-0ab0-4255-ab54-1b70442ca18c)
![Screenshot 2024-11-25 010409](https://github.com/user-attachments/assets/1a139709-9fa1-4fb0-9b22-4f0a44a9dc91)
