### ISSUE TITLE
Clear Text Immediately After Sending The Text

### ISSUE THREAD

**Issue by mohan-bee** [mohan-bee/DummyChat-React#3]
Issue:
 The text in the message box taking some time to clear 
Expected:
 The Text Must clear Immediately after sending the message

https://github.com/user-attachments/assets/0f3e4810-5ebc-42f0-974a-01119c3e4a4a

Expected @SahitSunny to Resolve this.

**Comment by SahitSunny** [comment]
This issue was already there, I will try to fix it

**Comment by mohan-bee** [comment]
> This issue was already there, I will try to fix it

Sounds Good

**Comment by artony4444** [comment]
location: src/Components/Chat.jsx
Line 58
```js
        try {
           
            await addDoc(messageRef, {
                text: newMessage,
                createdAt: serverTimestamp(),
                user: auth.currentUser.displayName,
                userId: auth.currentUser.uid,
                room,
            });


            setNewMessage(""); // <--- this is executing after addDoc()
...
```
setNewMessage() is getting executing after await addDoc()

I think this should woork

```js
        try {
            
            const messageText = newMessage; // <--- added
            setNewMessage(""); // <--- moved up
            
            await addDoc(messageRef, {
                text: messageText, // <--- changed
                createdAt: serverTimestamp(),
                user: auth.currentUser.displayName,
                userId: auth.currentUser.uid,
                room,
            });
```

**Comment by mohan-bee** [comment]
Your Approach Works Fine, Go ahead and work on this issue. 

Also, check that after sending message it first append on the top of the messages stack and then appending at the bottom

**Comment by mohan-bee** [comment]
@artony4444 @SahitSunny 
 If You would like to work with me connect with me in [slack](https://join.slack.com/t/4zero4workspace/shared_invite/zt-2ux3zfnbr-75YtzCiK3fqRTHqPFUGi7Q) that would be really interesting
